//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NportPrototypeControllerForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NportPrototypeControllerForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0e47472f49267ff01ac5977b6676287b {
            get {
                object obj = ResourceManager.GetObject("0e47472f49267ff01ac5977b6676287b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _106_512 {
            get {
                object obj = ResourceManager.GetObject("106-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _106_5121 {
            get {
                object obj = ResourceManager.GetObject("106-5121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _106_5122 {
            get {
                object obj = ResourceManager.GetObject("106-5122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _106_5122red {
            get {
                object obj = ResourceManager.GetObject("106-5122red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _106_5122white {
            get {
                object obj = ResourceManager.GetObject("106-5122white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _106_5122whiteThick {
            get {
                object obj = ResourceManager.GetObject("106-5122whiteThick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20150922134652_41901 {
            get {
                object obj = ResourceManager.GetObject("20150922134652_41901", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4d775e2a9a93231cf4f3515cc2a4ea0e__hero_wallpaper_wallpaper_desktop {
            get {
                object obj = ResourceManager.GetObject("4d775e2a9a93231cf4f3515cc2a4ea0e--hero-wallpaper-wallpaper-desktop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4d775e2a9a93231cf4f3515cc2a4ea0e__hero_wallpaper_wallpaper_desktop1 {
            get {
                object obj = ResourceManager.GetObject("4d775e2a9a93231cf4f3515cc2a4ea0e--hero-wallpaper-wallpaper-desktop1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _944806016 {
            get {
                object obj = ResourceManager.GetObject("944806016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9448060161 {
            get {
                object obj = ResourceManager.GetObject("9448060161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_legendary_pokemons_in_3d_wallpaper_by_genoforsmash_daq7whj {
            get {
                object obj = ResourceManager.GetObject("all_legendary_pokemons_in_3d_wallpaper_by_genoforsmash-daq7whj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_legendary_pokemons_in_3d_wallpaper_by_genoforsmash_daq7whj1 {
            get {
                object obj = ResourceManager.GetObject("all_legendary_pokemons_in_3d_wallpaper_by_genoforsmash-daq7whj1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_legendary_pokemons_in_3d_wallpaper_by_genoforsmash_daq7whj2 {
            get {
                object obj = ResourceManager.GetObject("all_legendary_pokemons_in_3d_wallpaper_by_genoforsmash-daq7whj2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ba87965c_382e_403d_b764_98f9baae54ac {
            get {
                object obj = ResourceManager.GetObject("ba87965c-382e-403d-b764-98f9baae54ac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bruno_rosal_tiny_dota2_collab_brunorosal {
            get {
                object obj = ResourceManager.GetObject("bruno-rosal-tiny-dota2-collab-brunorosal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap centaur_warrunner_foto {
            get {
                object obj = ResourceManager.GetObject("centaur-warrunner-foto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap derrick_song_crystal_maiden10_low {
            get {
                object obj = ResourceManager.GetObject("derrick-song-crystal-maiden10-low", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap djinn_slayer___bounty_hunter_by_chemicalalia_d75yl4i {
            get {
                object obj = ResourceManager.GetObject("djinn_slayer___bounty_hunter_by_chemicalalia-d75yl4i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap djinn_slayer___bounty_hunter_by_chemicalalia_d75yl4i1 {
            get {
                object obj = ResourceManager.GetObject("djinn_slayer___bounty_hunter_by_chemicalalia-d75yl4i1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DotA_2_Shadow_Demon_Wallpaper_700x360 {
            get {
                object obj = ResourceManager.GetObject("DotA-2-Shadow-Demon-Wallpaper-700x360", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dota2_chaos_knight_by_biggreenpepper_d69z1ks {
            get {
                object obj = ResourceManager.GetObject("dota2_chaos_knight_by_biggreenpepper-d69z1ks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dota2_razor_by_biggreenpepper_d6jcfuc {
            get {
                object obj = ResourceManager.GetObject("dota2_razor_by_biggreenpepper-d6jcfuc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dota2hq_eu_templar_assassin_wallpaper_for_pc_3843_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("dota2hq.eu-templar-assassin-wallpaper-for-pc-3843-1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lycanToEdit {
            get {
                object obj = ResourceManager.GetObject("lycanToEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maxresdefault__1_ {
            get {
                object obj = ResourceManager.GetObject("maxresdefault (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SandKing {
            get {
                object obj = ResourceManager.GetObject("SandKing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap steamworkshop_webupload_previewfile_165683781_preview {
            get {
                object obj = ResourceManager.GetObject("steamworkshop_webupload_previewfile_165683781_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap steamworkshop_webupload_previewfile_165683781_preview2 {
            get {
                object obj = ResourceManager.GetObject("steamworkshop_webupload_previewfile_165683781_preview2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap visage_dota_2_abstract_full_hd_wallpaper {
            get {
                object obj = ResourceManager.GetObject("visage-dota-2-abstract-full-hd-wallpaper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windrunner_dota_2_by_creat78_d5vpg2 {
            get {
                object obj = ResourceManager.GetObject("windrunner_dota_2_by_creat78-d5vpg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windrunner_dota_2_by_creat78_d5vpgnj {
            get {
                object obj = ResourceManager.GetObject("windrunner_dota_2_by_creat78-d5vpgnj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
